version: "3.9"

volumes:
  static_files:

services:

  # postgreSQL/ postGIS
  db:
    image: postgis/postgis:13-3.1
    hostname: ${HOSTNAME_PREFIX}db
    container_name: ${HOSTNAME_PREFIX}db
    volumes:
      - ${VOLUME_PREFIX}/postgresql/data:/var/lib/postgresql/data
      - ${VOLUME_PREFIX}/postgresql/backups:/backups
      - ${VOLUME_PREFIX}/log/postgresql:/var/log/postgresql
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
      - "5432"
    restart: on-failure

  # rabbitmq
  broker:
    image: rabbitmq:3.9-management
    hostname: ${HOSTNAME_PREFIX}broker
    container_name: ${HOSTNAME_PREFIX}broker
    environment:
      - RABBITMQ_DEFAULT_VHOST
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    # TODO: fix log file volume, has permissions error and refuses to start
    # volumes:
    #   - ${VOLUME_PREFIX}/log/rabbitmq:/var/log/rabbitmq
    expose:
      - "5672"
      - "15672"
    depends_on:
      - db
